bloggerhubproject/blogproject/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns=[
    path('register',views.register,name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),

]

bloggerhubproject/blogproject/blogapp/urls.py
from django.urls import path

from . import views
app_name ='blogapp'
urlpatterns =[
    path('',views.fun,name='fun'),
    # path('add',views.addition,name='add'),
    path('blog/<int:blog_id>',views.detail,name='detail'),
    path('add/',views.add_blog,name='add_blog'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

bloggerhubproject/blogproject/blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogapp.urls')),
    path('accounts/',include('accounts.urls')),


]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bloggerhubproject/blogproject/accounts/models.py
from django.db import models

# Create your models here.

bloggerhubproject/blogproject/blogapp/models.py
from django.db import models

# Create your models here.
class blog(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    image = models.ImageField(upload_to="image")

bloggerhubproject/blogproject/blogapp/forms.py
from.models import blog
from django import forms
class ModeForm(forms.ModelForm):
    class Meta:
        model=blog
        fields=['name','desc','image']

bloggerhubproject/blogproject/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
# Create your views here.
def login(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'invalid details')
            return redirect('login')
    else:
        return render(request,"login.html")
def register(request):
    if request.method=="POST":
        first_name=request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        if password1==password2:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username taken")
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email taken")
                return redirect('register')
            else:
               user=User.objects.create_user(username=username,password=password1,email=email,first_name=first_name,last_name=last_name)
               user.save();
               print("user created")
        else:
            print("password not matched")
            return redirect('register')

        return redirect('/')
    else:

        return render(request,'registration.html')
def logout(request):
    auth.logout(request)
    return redirect('/')

bloggerhubproject/blogproject/blogapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from . models import blog
from.forms import ModeForm

# Create your views here.
def fun(request):
  obj= blog.objects.all()
  return render(request, "index.html", {'results': obj})


# def addition(request):
#     num1 = int(request.POST["num1"])
#     num2 = int(request.POST["num2"])
#     num3 = num1+num2
#     return render(request,"result.html",{"add":num3})

def detail(request,blog_id):
    obj1 = blog.objects.get(id=blog_id)
    return render(request,"detail.html",{'results':obj1})

def add_blog(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        image=request.FILES['image']
        b=blog(name=name,desc=desc,image=image)
        b.save()
        print("blog added")
    return render(request,"add_blog.html")

def update(request,id):
    obj2 = blog.objects.get(id=id)
    form = ModeForm(request.POST or None, request.FILES,instance=obj2)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form, 'obj2':obj2})

def delete(request,id):
    if request.method=="POST":
      obj=blog.objects.get(id=id)
      obj.delete()
      return redirect('/')
    return render(request,'delete.html')

bloggerhubproject/blogproject/templates/add_blog.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="blog Name"><br>
    <input type="text" name="desc" placeholder="blog Caption"><br>
    <input type="file" name="image" placeholder="product Image"><br>
    <input type="submit" value="ADD">

</form>

bloggerhubproject/blogproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>avodha</title>
</head>
<body bgcolor="cyan">
{% block content %}
{% endblock %}

</body>
</html>

bloggerhubproject/blogproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    <strong>
    Are you sure you want to delete this item?
    </strong>
    <input type="submit">
</form>

bloggerhubproject/blogproject/templates/detail.html
<img src="{{results.image.url}}" alt="" style="width:250px;height:250px;" ><br>
{{results.name}}<br>
{{results.desc}}<br>

<a  href="{% url 'blogapp:update' results.id %}"><button>UPDATE</button></a>
<a  href="{% url 'blogapp:delete' results.id %}"><button>DELETE</button></a>

bloggerhubproject/blogproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="update">
</form>

bloggerhubproject/blogproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1> {{name}}</h1>
<form action="add" method="post">
     {% csrf_token %}
    number1 <input type="text" name="num1"><br>
    number2 <input type="text" name="num2"><br>
    <input type="submit" value="submit">
</form>

{% endblock %}

bloggerhubproject/blogproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="login">
</form>

</body>
</html>

bloggerhubproject/blogproject/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body>
<form action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="text" name="first_name" placeholder="firstname"><br>

    <input type="text" name="last_name" placeholder="lastname"><br>

    <input type="email" name="email" placeholder="email"><br>

    <input type="password" name="password1" placeholder="password"><br>
    <input type="password" name="password2" placeholder="confirm password"><br>
    <input type="submit" value="registration">
</form>
<div>
    {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</div>
</body>
</html>

bloggerhubproject/blogproject/templates/result.html
{% extends 'base.html' %}
{% block content %}
<h1>result is {{add}}</h1>
{% endblock %}